version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: jiayuan
      MYSQL_DATABASE: db-gpt
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=jiayuan
      - MYSQL_DATABASE=db-gpt
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network
    command: ["/app/wait-for-it.sh", "mysql", "3306", "--", "python", "main.py"]

volumes:
  mysql_data:

networks:
  app_network:
