version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: jiayuan
      MYSQL_DATABASE: db-gpt
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  gradio:
    build:
      context: .
      dockerfile: docker/Dockerfile  # 指定 Dockerfile 的相对路径
    container_name: gradio_app
    ports:
      - "7860:7860"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network
    command: ["/app/wait-for-it.sh", "mysql", "3306", "--", "python", "web_demo.py"]

volumes:
  mysql_data:

networks:
  app_network:
