version: '3'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql/
      - ./mysql/conf/:/etc/mysql/conf.d/
      #- ./deploy/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    networks:
      app_network:
        ipv4_address: 172.19.0.2
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  gradio:
    build:
      context: ..
      dockerfile: Dockerfile  # 指定 Dockerfile 的相对路径
    container_name: gradio_app
    ports:
      - "7860:7860"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      app_network:
        ipv4_address: 172.19.0.3
    command: ["python", "web_demo.py"]

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
