version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: app_builder
    environment:
      MYSQL_ROOT_PASSWORD: 'ls1234qwer'
      MYSQL_DATABASE: qianfan
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql/
      - ./deploy/sql/init_qianfan.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5


  fastapi:
    build:
      context: ..
      dockerfile: DockerfileAppbuilder
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=ls1234qwer
      - MYSQL_DATABASE=qianfan
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network
    command: ["/app/wait-for-it.sh", "mysql", "3306", "--", "python", "app_builder.py"]

volumes:
  mysql_data:

networks:
  app_network:
